---
    name: Build
    
    on:
      pull_request:
      push:
        branches:
          - master
      schedule:
        - cron: "10 2 * * 0"

    jobs:
      test:
        name: Test docker build
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2
    
          - name: Test building image
            run: docker build -t docker-ansible-cicd .

          - name: Run the built image.
            run: >-
              docker run --name test-container -d --privileged
              -v /sys/fs/cgroup:/sys/fs/cgroup:rw --cgroupns=host
              docker-ansible-cicd

          - name: Check Ansible is running
            run: docker exec --tty test-container env TERM=xterm ansible --version

      release:
        name: Release to Docker Hub
        runs-on: ubuntu-latest
        needs: test
        if: github.ref == 'refs/heads/master'

        steps:
          - uses: actions/checkout@v2
          - uses: docker/setup-qemu-action@v1
          - uses: docker/setup-buildx-action@v1

          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Build and push image.
            uses: docker/build-push-action@v2
            with:
              context: ./
              file: Dockerfile
              platforms: linux/amd64,linux/arm64
              push: true
              tags: ${{ github.repository }}:latest
